image: abstruse

matrix:
  - env: SCRIPT=lint NODE_VERSION=9
  - env: SCRIPT=test NODE_VERSION=9

before_install:
  - nvm install $NODE_VERSION
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

script:
  - npm run $SCRIPT

cache:
  - node_modules
